log4j.rootLogger=DEBUG, Console

# Console输出
log4j.appender.Console=org.apache.log4j.ConsoleAppender
log4j.appender.Console.layout=org.apache.log4j.PatternLayout
log4j.appender.Console.layout.ConversionPattern=%d [%t] %-5p [%c] - %m%n

# MyBatis日志
log4j.logger.com.example.dao=DEBUG
log4j.logger.org.mybatis=DEBUG
log4j.logger.org.springframework=INFO
